[tasks.lint]
dependencies = ["check-format-flow", "clippy-each-feature"]

[tasks.check-format]
env = { LEPTOS_PROJECT_DIRECTORY = "../" }
args = ["fmt", "--", "--check", "--config-path", "${LEPTOS_PROJECT_DIRECTORY}"]

[tasks.clippy-each-feature]
dependencies = ["install-clippy"]
command = "cargo"
args = ["hack", "clippy", "--workspace", "--each-feature", "--no-dev-deps", "--", "-Dclippy::all", "-Dclippy::pedantic"]
